spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jayram3436/Properties.git
          clone-on-start: true
server:
  port: 5889